QLTourism/Models/Slider.cs
namespace QLTourism.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Slider
    {
        public int id { get; set; }

        [StringLength(50)]
        [DisplayName("Title")]
        [Required(ErrorMessage = "Title không được để trống!")]
        public string name { get; set; }

        [StringLength(255)]
        [DisplayName("Ảnh bìa")]
        public string imagePath { get; set; }

        [StringLength(255)]
        [DisplayName("Đường dẫn")]
        public string urlPath { get; set; }
    }
}

QLTourism/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using QLTourism.Models;

namespace QLTourism.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        private TourismDB db = new TourismDB();

        // GET: Admin/Sliders
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
                ViewBag.currentSort = sortOrder;

                ViewBag.SapXepTheoId = String.IsNullOrEmpty(sortOrder) ? "id_asc" : "";
                ViewBag.SapXepTheoTen = sortOrder == "ten" ? "ten_desc" : "ten";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                ViewBag.currentFilter = searchString;
                var sliders = db.Sliders.Select(p => p);
                // Lọc nhân viên
                if (!String.IsNullOrEmpty(searchString))
                {
                    sliders = sliders.Where(p => p.name.Contains(searchString));
                }

                switch (sortOrder)
                {
                    case "id_asc":
                        sliders = sliders.OrderBy(s => s.id);
                        break;
                    case "ten":
                        sliders = sliders.OrderBy(s => s.name);
                        break;
                    case "ten_desc":
                        sliders = sliders.OrderByDescending(s => s.name);
                        break;
                    default:
                        sliders = sliders.OrderByDescending(s => s.id);
                        break;
                }
                int pageSize = 3;
                int pageNumber = (page ?? 1);
                return View(sliders.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/Sliders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Sliders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,imagePath,urlPath")] Slider slider, HttpPostedFileBase imagePath)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (imagePath != null && imagePath.ContentLength > 0)
                    {
                        string fileName = System.IO.Path.GetFileName(imagePath.FileName);
                        string urlImage = Server.MapPath("~/Areas/Admin/wwwroot/slider/" + DateTime.Now.ToString("ddMMyyyy_hhmmss_tt_") + fileName);
                        imagePath.SaveAs(urlImage);
                        slider.imagePath = DateTime.Now.ToString("ddMMyyyy_hhmmss_tt_") + fileName;
                    }
                    db.Sliders.Add(slider);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(slider);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu!" + ex.Message;
                return View(slider);
            }
        }

        // GET: Admin/Sliders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,urlPath")] Slider slider, HttpPostedFileBase editImage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Slider modifySlider = db.Sliders.Find(slider.id);
                    modifySlider.name = slider.name;
                    modifySlider.urlPath = slider.urlPath;
                    if (modifySlider != null)
                    {
                        if (editImage != null && editImage.ContentLength > 0)
                        {
                            string fileName = System.IO.Path.GetFileName(editImage.FileName);
                            string urlImage = Server.MapPath("~/Areas/Admin/wwwroot/slider/" + DateTime.Now.ToString("ddMMyyyy_hhmmss_tt_") + fileName);
                            editImage.SaveAs(urlImage);
                            modifySlider.imagePath = DateTime.Now.ToString("ddMMyyyy_hhmmss_tt_") + fileName;
                        }
                    }

                    db.Entry(modifySlider).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["imagePath"] = db.Sliders.Find(slider.id).imagePath;
                    return RedirectToAction("Index");
                }
                return View(slider);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu!" + ex.Message;
                return View(slider);
            }
        }

        // GET: Admin/Sliders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slider slider = db.Sliders.Find(id);
            try
            {
                db.Sliders.Remove(slider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu!" + ex.Message;
                return View(slider);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLTourism/Areas/Admin/Views/Slider/Create.cshtml
@model QLTourism.Models.Slider

@{
    ViewBag.Title = "Create";
    var ImagePath = "~/Areas/Admin/wwwroot/slider/slider.jpg";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm mới Sliders</h2>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@using (Html.BeginForm("Create", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="imagePath" id="imagePath input-file-now-custom-1" class="dropify" data-default-file="@Url.Content(@ImagePath)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.urlPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urlPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urlPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLTourism/Areas/Admin/Views/Slider/Delete.cshtml
@model QLTourism.Models.Slider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Xóa slider</h2>

<h3>Bạn có muốn xóa slider này?</h3>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urlPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urlPath)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLTourism/Areas/Admin/Views/Slider/Details.cshtml
@model QLTourism.Models.Slider

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Slider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>

        <dd>
            @{ 
                string ImagePath = "~/Areas/Admin/wwwroot/slider/" + Model.imagePath;
            }
            <img src="@Url.Content(ImagePath)"width="100"class="img-thumbnail" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urlPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urlPath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

QLTourism/Areas/Admin/Views/Slider/Edit.cshtml
@model QLTourism.Models.Slider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/Areas/Admin/wwwroot/slider/" + Model.imagePath;
}

<h2>Sửa</h2>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="editImage" id="editImage input-file-now-custom-1" class="dropify" data-default-file="@Url.Content(@ImagePath)" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.urlPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.urlPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.urlPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sửa" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLTourism/Areas/Admin/Views/Slider/Index.cshtml
@model PagedList.IPagedList<QLTourism.Models.Slider>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Quản lý Slider</h2>

<p>
    @*Html.ActionLink("Create New", "Create")*@
    <a class="btn btn-primary" href="@Url.Action("Create","Slider")" role="button">Thêm mới</a>
</p>
@using (Html.BeginForm())
{
    <p>
        Tìm kiếm theo tên slider: @Html.TextBox("searchString", ViewBag.currentFilter as string)
        <input type="submit" value="Tìm" class="btn btn-primary" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Tên danh mục", "Index", new { sortOrder = ViewBag.SapXepTheoTen, currentFilter = ViewBag.currentFilter })
        </th>
        <th>
            Ảnh bìa
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @if (item.imagePath != null)
                {
                    string ImagePath = "~/Areas/Admin/wwwroot/slider/" + item.imagePath;
                    <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                }
                else
                {
                    <img src="~/Areas/Admin/wwwroot/slider/slider.jpg" width="100" class="img-thumbnail" />
                }

            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.id }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))