QLTourism/Areas/Admin/Controllers/LoginController.cs
using QLTourism.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLTourism.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        private TourismDB db = new TourismDB();
        // GET: Admin/Login
        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            if (Session["idUser"] != null)
            {
                Session["Message"] = "Bạn đã đăng nhập!";
                return RedirectToAction("Index", "Dashboard");
            }
            return View(new User());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string username, string password)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = db.Users.Where(s => s.username.Equals(username) && s.password.Equals(password)).ToList();
                    if (data.Count() > 0)
                    {
                        //add session
                        Session["username"] = data.FirstOrDefault().username;
                        Session["idUser"] = data.FirstOrDefault().id;
                        Session["avatar"] = data.FirstOrDefault().avatar;
                        Session["roleId"] = data.FirstOrDefault().roleId;
                        return RedirectToAction("Index", "Dashboard");
                    }
                    else
                    {
                        Session["error"] = "Tài khoản hoặc mật khẩu không chính xác!";
                        return RedirectToAction("Index");
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi không thể đăng nhập!" + ex.Message;
                return View();
            }
        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Logout()
        {
            Session["username"] = null;
            Session["idUser"] = null;
            Session["avatar"] = null;
            Session["roleId"] = null;
            return RedirectToAction("Index");
        }
    }
}

QLTourism/Controllers/ClientLoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLTourism.Models;

namespace QLTourism.Views.Home
{
    public class ClientLoginController : Controller
    {
        private TourismDB db = new TourismDB();
        // GET: ClientLogin
        public ActionResult Index()
        {
            if (Session["ClientidUser"] != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult LoginPage(string username, string password, string returnUrl)
        {
            if (!String.IsNullOrEmpty(returnUrl))
                ViewBag.oldUrl = returnUrl;
            if (Session["ClientidUser"] != null)
            {
                if(!String.IsNullOrEmpty(returnUrl))
                    return Redirect(returnUrl);
                return RedirectToAction("Index", "Home");
            }
            else if(!String.IsNullOrEmpty(username)&& !String.IsNullOrEmpty(password))
            {
                var tk = db.Customers.Where(p => p.username.Equals(username) && p.password.Equals(password)).FirstOrDefault();
                if (tk != null)
                {
                    Session["ClientidUser"] = tk.id;
                    Session["ClientUsername"] = tk.username;
                    Session["ClientName"] = tk.name;
                    Session["ClientAvatar"] = tk.avatar;
                    if (!String.IsNullOrEmpty(returnUrl))
                        return Redirect(returnUrl);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Error = "Sai tên tài khoản hoặc mật khẩu!";
                }
            }
            else if (username != null && password != null)
            {
                if (username.Equals("") || password.Equals(""))
                {
                    ViewBag.Error = "Sai tên tài khoản hoặc mật khẩu!";
                    return View();
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult ValidateUser(string username, string password)
        {
            var tk = db.Customers.Where(p => p.username.Equals(username) && p.password.Equals(password)).FirstOrDefault();
            if (tk != null)
            {
                Session["ClientidUser"] = tk.id;
                Session["ClientUsername"] = tk.username;
                Session["ClientName"] = tk.name;
                Session["ClientAvatar"] = tk.avatar;
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
        }
        public new ActionResult Profile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: /ClientLogin/EditProfile/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile([Bind(Include = "id,username,password,name,email,phone,gender,city,country,birthday,address")] Customer customer, HttpPostedFileBase editImage)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Customer modifyCustomer = db.Customers.Find(customer.id);
                    modifyCustomer.username = customer.username;
                    modifyCustomer.password = customer.password;
                    modifyCustomer.name = customer.name;
                    modifyCustomer.email = customer.email;
                    modifyCustomer.phone = customer.phone;
                    modifyCustomer.gender = customer.gender;
                    modifyCustomer.city = customer.city;
                    modifyCustomer.country = customer.country;
                    modifyCustomer.birthday = customer.birthday;
                    modifyCustomer.address = customer.address;
                    if (modifyCustomer != null)
                    {
                        if (editImage != null && editImage.ContentLength > 0)
                        {
                            string fileName = System.IO.Path.GetFileName(editImage.FileName);
                            string urlImage = Server.MapPath("~/Assets/img/images/" + DateTime.Now.ToString("ddMMyyyy_hhmmss_tt_") + fileName);
                            editImage.SaveAs(urlImage);
                            modifyCustomer.avatar = DateTime.Now.ToString("ddMMyyyy_hhmmss_tt_") + fileName;
                        }
                    }
                    db.Entry(modifyCustomer).State = EntityState.Modified;
                    db.SaveChanges();
                    Session["ClientAvatar"] = db.Customers.Find(customer.id).avatar;
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Đã xảy ra lỗi " + ex.Message;
                return View(customer);
            }
        }

        public ActionResult Logout(string returnUrl)
        {
            Session["ClientidUser"] = null;
            Session["ClientUsername"] = null;
            Session["ClientName"] = null;
            Session["ClientAvatar"] = null;
            if (!String.IsNullOrEmpty(returnUrl))
                return Redirect(returnUrl);
            return RedirectToAction("Index", "Home");
        }
        [ChildActionOnly]
        public ActionResult login()
        {
            return PartialView();
        }

    }
}

QLTourism/Views/ClientLogin/LoginPage.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Đăng nhập OKAYU</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="~/Assets/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="~/Assets/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="~/Assets/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="~/Assets/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="~/Assets/img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <link href="~/Assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Assets/css/style.css" rel="stylesheet">
    <link href="~/Assets/css/vendors.css" rel="stylesheet">

    <!-- YOUR CUSTOM CSS -->
    <link href="~/Assets/css/custom.css" rel="stylesheet">

    @{
        Layout = null;
    }

</head>
@if (Session["Message"] != null)
{
    <div class="alert alert-danger float-lg-right" role="alert">@Session["Message"]</div>
    Session["Message"] = null;
}
<body id="login_bg" style="background: url(@Url.Content("/Assets/img/sectionCallBG.jpg")) center center no-repeat !important; background-size:cover;">

    <nav id="menu" class="fake_menu"></nav>

    <!-- End Preload -->
    <div id="login">
        <aside>
            <figure>
                <a href="/Home/index/"><img src="~/Assets/img/logo_sticky.png" width="155" height="36" data-retina="true" alt="" class="logo_sticky"></a>
            </figure>
            <form>
                <div class="access_social">
                    <a href="#0" class="social_bt facebook">Đăng nhập bằng Facebook</a>
                    <a href="#0" class="social_bt google">Đăng nhập bằng Google</a>
                </div>
                <div class="divider"><span>Or</span></div>
                <div class="form-group">
                    <label>Tên đăng nhập</label>
                    <input type="text" class="form-control" name="username" id="username">
                    <i class="icon_mail_alt"></i>
                </div>
                <div class="form-group">
                    <label>Mật khẩu</label>
                    <input type="password" class="form-control" name="password" id="password" value="">
                    <i class="icon_lock_alt"></i>
                </div>
                <input type="hidden" name="returnUrl" value="@ViewBag.oldUrl" />
                <div class="clearfix add_bottom_30">
                    <div class="checkboxes float-left">
                        <label class="container_check">
                            Ghi nhớ tôi
                            <input type="checkbox">
                            <span class="checkmark"></span>
                        </label>
                    </div>
                    <div class="float-right mt-1"><a id="forgot" href="javascript:void(0);">Quên mật khẩu?</a></div>
                </div>
                <p class="text-center bg-danger">@ViewBag.Error</p>
                <input type="submit" class="btn_1 rounded full-width" value="Đăng nhập" />
                <div class="text-center add_top_10">Bạn là người mới? <strong><a href="/Register/index/">Đăng ký!</a></strong></div>
            </form>
            <div class="copy">© 2021 Okayu</div>
        </aside>
    </div>
    <!-- /login -->
    <!-- COMMON SCRIPTS -->
    <script src="~/Assets/js/jquery-2.2.4.min.js"></script>
    <script src="~/Assets/js/common_scripts.js"></script>
    <script src="~/Assets/js/main.js"></script>
    <script src="~/Assets/assets/validate.js"></script>

</body>
</html>

QLTourism/Views/ClientLogin/Profile.cshtml
@model QLTourism.Models.Customer

@{
    ViewBag.Title = "Chỉnh sửa thông tin cá nhân";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var ImagePath = "~/Assets/img/images/" + Model.avatar;
}

<div class="container-fluid margin_80_0" style="background-color: SkyBlue;">
    @using (Html.BeginForm("EditProfile", "ClientLogin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <h5 style="color:white;">Sửa thông tin</h5>
        @Html.AntiForgeryToken()

        <div class="card-body" style="background-color:white;">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.avatar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    <input type="file" name="editImage" src="@Url.Content(@ImagePath)" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.RadioButtonFor(model => model.gender, true) Nam
                        @Html.RadioButtonFor(model => model.gender, false) Nữ
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.birthday, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.birthday, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu thông tin" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
    @Html.ActionLink("Quay lại", "Index")
</div>

QLTourism/Views/ClientLogin/login.cshtml
<div id="sign-in-dialog" class="zoom-anim-dialog mfp-hide">
    <div class="small-dialog-header">
        <h3>Đăng nhập</h3>
    </div>
    <div id="signInHiddenForm">
        <div class="sign-in-wrapper">
            <a href="#0" class="social_bt facebook">Đăng nhập với Facebook</a>
            <a href="#0" class="social_bt google">Đăng nhập với Google</a>
            <div class="divider"><span>Hoặc</span></div>
            <div class="form-group">
                <label>Tên đăng nhập</label>
                <input type="text" class="form-control hiddenFormInput" name="usernameHidden" id="username">
                <i class="icon_mail_alt"></i>
            </div>
            <div class="form-group">
                <label>Mật khẩu</label>
                <input type="password" class="form-control hiddenFormInput" name="passwordHidden" id="password" value="">
                <i class="icon_lock_alt"></i>
            </div>
            <div class="clearfix add_bottom_15">
                <div class="checkboxes float-left">
                    <label class="container_check">
                        Ghi nhớ!
                        <input type="checkbox">
                        <span class="checkmark"></span>
                    </label>
                </div>
                <div class="float-right mt-1"><a id="forgot" href="javascript:void(0);">Quên mật khẩu?</a></div>
            </div>
            <div class="text-center"><a class="btn_1 full-width" id="submitBtn">Đăng nhập</a></div>
            <div class="text-center">
                Bạn chưa có tài khoản? <a href="/register/index">Đăng ký</a>
            </div>
            <div id="forgot_pw">
                <div class="form-group">
                    <label>Vui lòng xác nhận địa chỉ email</label>
                    <input type="email" class="form-control" name="email_forgot" id="email_forgot">
                    <i class="icon_mail_alt"></i>
                </div>
                <p>Bạn sẽ nhận được email để reset lại thành mật khẩu mới</p>
                <div class="text-center"><input type="submit" value="Lấy lại mật khẩu" class="btn_1"></div>
            </div>
        </div>
    </div>
    <!--form -->
</div>
<script src="~/Assets/js/jquery-2.2.4.min.js"></script>
<script>
    $(document).ready(function () {
        $(function () {
            $(".hiddenFormInput").keyup(function (event) {
                if (event.keyCode === 13) {
                    loginHidden();
                }
            });
        });
        $('#submitBtn').click(function () {
            loginHidden();
        });
        function loginHidden() {
            var data = {
                "username": $("#username").val(),
                "password": $("#password").val()
            };
            $.ajax({
                url: "/ClientLogin/ValidateUser",
                type: "POST",
                data: JSON.stringify(data),
                dataType: "json",
                contentType: "application/json",
                success: function (response) {
                    if (response.Success) {
                        window.location.href = "@Request.RawUrl"
                     }
                    else
                        alert("Sai tài khoản hoặc mật khẩu!")
                },
                error: function () {

                }
            });
        }
    });
</script>