QLTourism/Controllers/NewsViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLTourism.Models;
using System.Data.Entity;

namespace QLTourism.Controllers
{
    public class NewsViewController : Controller
    {
        private TourismDB db = new TourismDB();
        // GET: News
        public ActionResult Index(string searchString)
        {
            var newsz = db.News.Select(p => p);
            if (!String.IsNullOrEmpty(searchString))
            {
                newsz = newsz.Where(p => p.title.Contains(searchString));
            }
            newsz = newsz.OrderByDescending(p => p.id);
            ViewBag.searchString = searchString;
            return View(newsz.ToList());
        }
        // GET: News
        public ActionResult ArticleDetail(int? id)
        {
            var newsz = db.News.Find(id);
            return View(newsz);
        }
        public ActionResult SideMenu()
        {
            var newsz = db.News.Select(p => p);
            newsz = newsz.OrderByDescending(p => p.id);
            return PartialView(newsz.ToList());
        }
    }
}

QLTourism/Views/NewsView/ArticleDetail.cshtml
@model QLTourism.Models.News
@{
    ViewBag.Title = Model.title;
    Layout = "~/Views/Shared/_Layout.cshtml";
    string ImagePath = "~/Areas/Admin/wwwroot/thumbail/" + Model.thumbail;
}

<!-- SPECIFIC CSS -->
<link href="~/Assets/css/blog.css" rel="stylesheet">

<section class="hero_in general" style="background: url(@Url.Content(ImagePath)) center center no-repeat @if (Model.thumbail != null) { Html.Raw("!important"); }; background-size:cover;">
    <div class="wrapper">
        <div class="container">
            <h1 class="fadeInUp"><span></span>tin tức</h1>
        </div>
    </div>
</section>
<!--/hero_in-->

<div class="container margin_60_35">
    <div class="row">
        <div class="col-lg-9">
            <div class="bloglist singlepost">
                <p><img alt="" class="img-fluid" src="img/blog-single.jpg"></p>
                <h1>@Model.title</h1>
                <div class="postmeta">
                    <ul><li><a href="#"><i class="icon_clock_alt"></i> @{string a = Model.date.ToString().Split(' ')[0]; @a}</a></li>
                    </ul>
                </div>
                <!-- /post meta -->
                <div class="post-content">
                    <p>@Model.summary</p>
                    <hr />
                    <p>@Html.Raw(Model.detail)</p>
                </div>
                <!-- /post -->
            </div>
            <!-- /single-post -->
         </div>
        <aside class="col-lg-3">
            @{ Html.RenderAction("SideMenu", "NewsView");}
        </aside>
        <!-- /aside -->
    </div>
    <!-- /row -->
</div>
<!-- /container -->

QLTourism/Views/NewsView/Index.cshtml
@model IEnumerable<QLTourism.Models.News>
@{
    ViewBag.Title = "Xem tin tức - Okayu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- SPECIFIC CSS -->
<link href="~/Assets/css/blog.css" rel="stylesheet">

<section class="hero_in general" style="background: url(@Url.Content("~/Assets/img/NewsBG.jpg")) center center no-repeat !important; ; background-size:cover !important;">
    <div class="wrapper">
        <div class="container">
            <h1 class="fadeInUp"><span></span>Tin tức</h1>
        </div>
    </div>
</section>
<!--/hero_in-->

<div class="container margin_60_35">
    <div class="row">
        <div class="col-lg-9">
            @foreach (var item in Model)
            {
                string ImagePath = "~/Areas/Admin/wwwroot/thumbail/" + item.thumbail;
                <article class="blog wow fadeIn">
                    <div class="row no-gutters">
                        <div class="col-lg-7">
                            <figure>
                                <a href="/NewsView/ArticleDetail/@item.id">
                                    <img src="@Url.Content(ImagePath)" alt="">
                                    <div class="preview"><span>Xem thêm</span></div>
                                </a>
                            </figure>
                        </div>
                        <div class="col-lg-5">
                            <div class="post_info">
                                <small>@{string a = item.date.ToString().Split(' ')[0]; @a}</small>
                                <h3><a href="/NewsView/ArticleDetail/@item.id">@item.title</a></h3>
                                <p>@item.summary</p>
                            </div>
                        </div>
                    </div>
                </article>
                <!-- /article -->
            }
        </div>
        <!-- /col -->

        <aside class="col-lg-3">
            @{ Html.RenderAction("SideMenu", "NewsView");}
        </aside>
        <!-- /aside -->
    </div>
    <!-- /row -->
</div>
<!-- /container -->

QLTourism/Views/NewsView/SideMenu.cshtml
@model IEnumerable<QLTourism.Models.News>


<!-- /widget -->
<div class="widget">
    <form action="/NewsView/Index">
        <div class="form-group">
            <input type="text" name="searchString" id="search" class="form-control" placeholder="Tìm kiếm...">
        </div>
        <button type="submit" id="submit" class="btn_1 rounded">Tìm kiếm</button>
    </form>
</div>
<div class="widget">
    <div class="widget-title">
        <h4>Bài đăng gần đây</h4>
    </div>
    <ul class="comments-list">
        @{
            int i = 0;
            foreach (var item in Model)
            {
                int z = 35;
                if (item.title.Length <= 35)
                {
                    z = item.title.Length - 3;
                }
                string ImagePath = "~/Areas/Admin/wwwroot/thumbail/" + item.thumbail;
                <li>
                    <div class="alignleft">
                        <a href="#0"><img src="@Url.Content(ImagePath)" alt=""></a>
                    </div>
                    <small>@{string a = item.date.ToString().Split(' ')[0]; @a}</small>
                    <h3><a href="#" title="">@item.title.Substring(0, z) ...</a></h3>
                </li>
            }
        }
    </ul>
</div>